services:
  - type: web
    name: bidserve-api
    runtime: node
    region: oregon
    plan: free
    envVars:
      - key: PORT
        value: 3001
      - key: JWT_SECRET
        generateValue: true
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /
